"use client";

import Link from "next/link";
import { Check, CreditCard, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import useTitle from "@/hooks/useTitle";

export default function BrokerPlan() {
  useTitle("Broker plan");
  const [plan, setPlan] = useState<{ code: string; active: boolean; monthlyCredits: number; usedCredits: number; remainingCredits: number; entitlements: string[] } | null>(null);
  useEffect(() => { fetch("/api/account/plan", { cache: "no-store" }).then((response) => response.json()).then((payload) => { if (payload.ok) setPlan(payload.plan); }).catch(() => undefined); }, []);
  return <div className="bg-paper pb-20 pt-[78px] text-ink"><div className="container py-12"><p className="kicker text-brick">Broker access · verified inventory</p><h1 className="display mt-4 max-w-3xl text-[clamp(40px,6vw,72px)]">The right contact, not every contact.</h1><p className="mt-5 max-w-2xl text-base leading-8 ink-2">Architech keeps owner numbers masked and makes qualified inventory available through auditable plan entitlements, relay contact, and owner-approved address requests.</p><div className="mt-10 grid gap-5 lg:grid-cols-[1fr_1.2fr]"><section className="border border-ink/12 bg-card p-7"><div className="flex items-start justify-between"><CreditCard className="text-brick" /><span className="stamp ink-3">CURRENT ACCESS</span></div><p className="mt-8 font-display text-3xl">{plan?.code ?? "Loading…"}</p><p className="mt-2 text-sm ink-2">{plan?.active ? "Active entitlement" : "Free discovery access"}</p><div className="mt-7 border-t border-ink/10 pt-5"><p className="stamp ink-3">Contact credits</p><p className="mt-2 font-display text-4xl">{plan ? `${plan.remainingCredits} / ${plan.monthlyCredits}` : "—"}</p><p className="mt-2 text-sm ink-2">Relay contact credits remaining this month</p></div></section><section className="border border-ink/12 bg-night p-7 text-cream"><div className="flex items-start justify-between"><ShieldCheck className="text-ember" /><span className="stamp text-ember">WHAT IS INCLUDED</span></div><ul role="list" aria-label="Broker plan benefits" className="mt-8 space-y-4 text-sm leading-6 text-cream">{["Owner-direct and broker-shareable inventory filters", "Relay call and WhatsApp workflows without raw-number exposure", "Audited contact credits and organisation-scoped access", "Exact-address requests that still require advertiser approval"].map((item) => <li key={item} className="flex gap-3"><Check size={16} className="mt-1 shrink-0 text-ember" />{item}</li>)}</ul><Link href="/broker/inventory/" className="mt-8 inline-flex min-h-11 items-center bg-brick clay-fill px-5 py-3 stamp font-semibold text-cream">Browse verified inventory</Link></section></div><p className="mt-8 max-w-2xl text-xs leading-6 ink-3">A plan makes you eligible for controlled access. It does not override the owner’s consent, address policy, suppression choice, or Architech safety review. Payment activation is not connected in this preview.</p></div></div>;
}
