/* Architech Editorial Terracotta: crawlable locality authority page with visible facts, source context, trust, inventory, and internal links. */
import { ArrowUpRight, Check, Clock3, MapPin, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import PropertyCard, { properties } from "../components/architech/PropertyCard";

export default function CityPage() {
  return <div className="bg-paper pt-[76px] text-ink">
    <section className="border-b border-ink/10 bg-limestone py-14 md:py-20"><div className="container"><div className="flex flex-wrap items-center gap-2 text-xs font-medium text-ink/55"><Link href="/" className="hover:text-clay">Home</Link><span>/</span><Link href="/buy/mumbai/" className="hover:text-clay">Buy in Mumbai</Link><span>/</span><span>Bandra West</span></div><div className="mt-12 grid gap-10 md:grid-cols-[1.2fr_.8fr] md:items-end"><div><p className="arch-line text-[11px] font-semibold uppercase tracking-[.2em] text-clay">A locality, in context</p><h1 className="mt-5 max-w-[720px] font-display text-5xl font-medium leading-[.9] tracking-[-.065em] md:text-7xl">Homes in Bandra West, Mumbai</h1><p className="mt-6 max-w-[580px] text-lg leading-8 text-ink/65">Sea-facing edges, independent cafes, old trees, and a pace that shifts street by street. Explore homes with the context around them.</p></div><div className="border-l-4 border-[var(--clay)] bg-paper p-6 editorial-shadow md:mb-2"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-ink/50">Locality snapshot</p><div className="mt-5 grid grid-cols-2 gap-5"><div><strong className="font-display text-3xl">128</strong><p className="text-xs text-ink/55">active homes</p></div><div><strong className="font-display text-3xl">4.8 km</strong><p className="text-xs text-ink/55">to Bandra station</p></div></div><p className="mt-5 flex items-center gap-2 border-t border-ink/10 pt-4 text-xs text-ink/50"><Clock3 size={13} /> Updated 21 Aug 2026 · Sources reviewed</p></div></div></div></section>
    <section className="container py-16 md:py-24"><div className="grid gap-12 md:grid-cols-[1fr_1.35fr]"><div><p className="arch-line text-[11px] font-semibold uppercase tracking-[.2em] text-clay">What the place feels like</p><h2 className="mt-5 font-display text-4xl font-medium leading-[.98] tracking-[-.05em]">A neighbourhood with a front door and a backstory.</h2><p className="mt-6 text-base leading-7 text-ink/65">Bandra West balances a residential rhythm with a generous everyday life: walkable lanes, independent places to eat, access to the coast, and a strong mix of established and newer homes.</p><div className="mt-8 grid gap-3 text-sm text-ink/70"><p className="flex items-center gap-3"><Check size={16} className="text-clay" /> Walkable pockets around Hill Road</p><p className="flex items-center gap-3"><Check size={16} className="text-clay" /> Cafes, schools, and everyday retail close by</p><p className="flex items-center gap-3"><Check size={16} className="text-clay" /> Strong mix of resale and new projects</p></div></div><div className="overflow-hidden"><img src="/manus-storage/architech-locality-editorial_3d96042e.jpg" alt="Tree-lined street in Bandra West, Mumbai" className="aspect-[1.45] h-full w-full object-cover" /></div></div></section>
    <section className="bg-ink py-14 text-paper"><div className="container grid gap-8 md:grid-cols-[.75fr_1.25fr] md:items-center"><div><div className="flex items-center gap-2 text-[#f0b59b]"><ShieldCheck size={17} /><span className="text-[11px] font-semibold uppercase tracking-[.17em]">Trust note</span></div><h2 className="mt-4 font-display text-3xl leading-tight">Every home tells you where its information came from.</h2></div><p className="max-w-xl text-sm leading-7 text-paper/65">Listing status, broker identity, RERA context where applicable, and the last meaningful update are designed to be visible—not buried in an FAQ.</p></div></section>
    <section className="container py-20 md:py-28"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="arch-line text-[11px] font-semibold uppercase tracking-[.2em] text-clay">Available now</p><h2 className="mt-5 font-display text-4xl font-medium tracking-[-.05em] md:text-5xl">Homes worth a closer look</h2></div><Link href="/search" className="inline-flex items-center gap-2 text-sm font-semibold text-clay">See all Bandra West homes <ArrowUpRight size={16} /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{properties.map((property) => <PropertyCard key={property.id} property={property} />)}</div></section>
    <section className="border-t border-ink/10 bg-limestone py-16"><div className="container"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-clay">Explore nearby</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/buy/mumbai/" className="inline-flex items-center gap-2 border border-ink/20 bg-paper px-4 py-3 text-sm font-semibold hover:border-clay">Khar West <MapPin size={14} /></Link><Link href="/buy/mumbai/" className="inline-flex items-center gap-2 border border-ink/20 bg-paper px-4 py-3 text-sm font-semibold hover:border-clay">Powai <MapPin size={14} /></Link><Link href="/guide" className="inline-flex items-center gap-2 border border-ink/20 bg-paper px-4 py-3 text-sm font-semibold hover:border-clay">Read locality notes <ArrowUpRight size={14} /></Link></div></div></section>
  </div>;
}
