"use client";
/* India-wide developer index: evidence-led directory, not paid ranking. */
import Link from "next/link";
import { ArrowUpRight, Check, MapPinned } from "lucide-react";
import Reveal from "@/components/architech/Reveal";

const directory = [
  { name: "Architech Curated Homes", kind: "Curated collection", note: "A small, source-reviewed set of homes with locality context.", locality: "Paldi · Thaltej · Navrangpura", projects: 3 },
  { name: "Nivasa Partners", kind: "Verified partner", note: "Partner inventory shown with a freshness signal and a masked contact path.", locality: "Prahlad Nagar", projects: 1 },
  { name: "India builder index", kind: "Directory in progress", note: "A city-scoped index for builders whose project and applicable RERA documents can be reviewed before publication.", locality: "Reviewed cities", projects: 0 },
];

export default function DeveloperIndexPage({ listingCount }: { listingCount: number }) {
  return (
    <div className="bg-paper pt-[78px] text-ink">
      <section className="border-b border-ink/12 bg-sand/60 py-20 md:py-32"><div className="container grid gap-10 lg:grid-cols-[1fr_0.65fr] lg:items-end"><Reveal><p className="kicker text-brick">Builder and project index · India</p><h1 className="display mt-6 max-w-[850px] text-[clamp(46px,8vw,108px)]">Meet the people who <em className="text-brick">shape</em> the city.</h1><p className="mt-7 max-w-xl text-[15px] leading-7 text-ink/65">A developer directory is useful only when it gives you context: where a group builds, what is published, and which facts have been checked.</p></Reveal><Reveal delay={120} className="border-l-2 border-brick pl-6"><p className="font-display text-5xl tracking-[-0.04em]">{listingCount}</p><p className="stamp mt-2 !text-[10px] text-ink/60">curated listings currently connected to the index</p></Reveal></div></section>
      <section className="container py-20 md:py-28"><div className="flex items-end justify-between gap-6 border-b border-ink/15 pb-5"><div><p className="kicker text-brick">Directory, not leaderboard</p><h2 className="mt-3 font-display text-4xl font-medium tracking-[-0.03em]">Search the builders behind the address.</h2></div><span className="stamp !text-[10px] text-ink/50">Phase 1 · evidence-first</span></div><div className="divide-y divide-ink/15 border-b border-ink/15">{directory.map((developer, index) => <Reveal key={developer.name} delay={index * 70}><article className="grid gap-6 py-8 md:grid-cols-[90px_1fr_auto] md:items-center"><span className="index-num text-4xl text-brick/70">{String(index + 1).padStart(2, "0")}</span><div><div className="flex flex-wrap items-center gap-3"><h3 className="font-display text-3xl font-medium tracking-[-0.03em]">{developer.name}</h3><span className="stamp border border-trust/30 px-2 py-1 !text-[9px] text-trust">{developer.kind}</span></div><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/65">{developer.note}</p><p className="mt-4 flex items-center gap-2 stamp !text-[10px] text-ink/55"><MapPinned size={12} className="text-brick" />{developer.locality} · {developer.projects ? `${developer.projects} linked projects` : "review queue"}</p></div><Link href={developer.projects ? "/search/" : "/requirements/"} className="inline-flex items-center gap-2 stamp !text-[11px] font-semibold text-brick">{developer.projects ? "View related homes" : "Request a review"}<ArrowUpRight size={14} /></Link></article></Reveal>)}</div></section>
      <section className="border-y border-ink/12 bg-night py-20 text-cream md:py-28"><div className="container grid gap-10 lg:grid-cols-[1fr_0.8fr]"><div><p className="kicker text-ember">What gets published</p><h2 className="display mt-5 max-w-2xl text-[clamp(36px,5vw,66px)]">A name is not enough. Show the <em className="text-ember">trail.</em></h2></div><div className="grid gap-4">{["Project and locality are explicit.", "RERA context is visible when applicable.", "Freshness is stamped, not implied.", "Paid placement never becomes a trust badge."].map((item) => <p key={item} className="flex items-start gap-3 border-b border-cream/15 pb-4 text-sm leading-6 text-cream/70"><Check size={16} className="mt-1 shrink-0 text-ember" />{item}</p>)}</div></div></section>
    </div>
  );
}
