/* Architech Editorial Terracotta: Ahmedabad-first home, place-led discovery, trust before spectacle, and purposeful motion. */
import { ArrowDownRight, ArrowUpRight, Compass, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";
import PropertyCard, { properties } from "../components/architech/PropertyCard";
import Reveal from "../components/architech/Reveal";

const localities = [
  { name: "Paldi", note: "Tree-lined, central, quietly established", homes: "42 homes" },
  { name: "Prahlad Nagar", note: "Newer buildings, easy everyday rhythm", homes: "68 homes" },
  { name: "Thaltej", note: "Room to breathe at the city’s western edge", homes: "54 homes" },
  { name: "Navrangpura", note: "Lively streets with a familiar pulse", homes: "31 homes" },
];

export default function Home() {
  return <div className="bg-paper text-ink">
    <section className="relative min-h-[720px] overflow-hidden bg-ink text-paper md:min-h-[790px]">
      <img src="/manus-storage/architech-ahmedabad-hero_ca336401.jpg" alt="Ahmedabad homes and skyline at golden hour" className="hero-image-motion absolute inset-0 h-full w-full object-cover opacity-80" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(30,27,23,.88)_0%,rgba(30,27,23,.56)_44%,rgba(30,27,23,.08)_100%)]" />
      <div className="relative z-10 container flex min-h-[720px] flex-col justify-between py-32 md:min-h-[790px] md:py-40">
        <div className="max-w-3xl arch-rise"><div className="mb-7 flex items-center gap-3 text-[11px] font-semibold uppercase tracking-[.22em] text-[#efb094]"><span className="h-px w-20 bg-[#efb094]" /> Ahmedabad, considered differently</div><h1 className="max-w-[760px] font-display text-6xl font-medium leading-[.88] tracking-[-.075em] text-paper md:text-8xl">Find the place<br /><em className="font-display not-italic text-[#efb094]">before</em> you choose<br />the home.</h1><p className="mt-8 max-w-[440px] text-base leading-7 text-paper/75 md:text-lg">A more considered way to explore Ahmedabad—where locality context, verified facts, and homes worth returning to meet in one calm experience.</p></div>
        <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><Link href="/buy/ahmedabad/" className="motion-press group inline-flex w-fit items-center gap-6 bg-paper px-6 py-5 text-sm font-semibold text-ink transition-transform duration-200 hover:-translate-y-1"><span>Start with a locality</span><ArrowUpRight size={18} className="text-clay transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></Link><p className="max-w-[220px] text-xs leading-5 text-paper/55 md:text-right">Public facts first. The right next step, when you are ready.</p></div>
      </div>
    </section>
    <section className="relative z-10 -mt-px border-b border-ink/15 bg-paper"><div className="container grid divide-y divide-ink/15 md:grid-cols-3 md:divide-x md:divide-y-0"><div className="py-7 pr-7"><ShieldCheck size={18} className="text-clay" /><p className="mt-4 font-display text-xl">Evidence, not noise.</p><p className="mt-2 text-sm leading-6 text-ink/60">RERA context, source notes, and freshness stay visible when they matter.</p></div><div className="py-7 md:px-7"><Compass size={18} className="text-clay" /><p className="mt-4 font-display text-xl">A place before an address.</p><p className="mt-2 text-sm leading-6 text-ink/60">Understand how Ahmedabad feels street by street before you shortlist a home.</p></div><div className="py-7 md:pl-7"><Sparkles size={18} className="text-clay" /><p className="mt-4 font-display text-xl">Search with intention.</p><p className="mt-2 text-sm leading-6 text-ink/60">Simple filters, helpful suggestions, and no maze of empty pages.</p></div></div></section>
    <section className="container py-20 md:py-28"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="arch-line text-[11px] font-semibold uppercase tracking-[.2em] text-clay">A beginning, not a shortlist</p><h2 className="mt-5 max-w-[620px] font-display text-5xl font-medium leading-[.94] tracking-[-.065em] md:text-6xl">The right place changes the shape of a day.</h2></div><Link href="/buy/ahmedabad/" className="inline-flex items-center gap-2 text-sm font-semibold text-clay">Browse Ahmedabad <ArrowUpRight size={16} /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{properties.map((property, index) => <Reveal key={property.id} delay={index * 90}><PropertyCard property={property} /></Reveal>)}</div></section>
    <section className="bg-limestone py-20 md:py-28"><div className="container grid gap-12 md:grid-cols-[.8fr_1.2fr] md:items-start"><div><p className="arch-line text-[11px] font-semibold uppercase tracking-[.2em] text-clay">Choose your starting point</p><h2 className="mt-5 max-w-[420px] font-display text-4xl font-medium leading-none tracking-[-.055em] md:text-5xl">A city is more than a pin on a map.</h2><p className="mt-5 max-w-[380px] text-sm leading-7 text-ink/60">Begin with a locality, and we’ll help you understand what living there might feel like.</p></div><div className="border-t border-ink/20">{localities.map((place, index) => <Link key={place.name} href="/buy/ahmedabad/" style={{ animationDelay: `${index * 70}ms` }} className="group flex items-center justify-between gap-5 border-b border-ink/20 py-5 transition-colors hover:bg-paper/50 motion-lift"><div><p className="font-display text-2xl tracking-[-.03em]">{place.name}</p><p className="mt-1 text-sm text-ink/55">{place.note}</p></div><div className="flex items-center gap-3 text-right text-xs text-ink/50"><span>{place.homes}</span><ArrowUpRight size={16} className="text-clay transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div></Link>)}</div></div></section>
    <section className="bg-ink py-24 text-paper"><div className="container grid gap-12 md:grid-cols-[.9fr_1.1fr] md:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.2em] text-[#efb094]">Our point of view</p><h2 className="mt-5 max-w-[560px] font-display text-5xl font-medium leading-[.94] tracking-[-.06em] md:text-6xl">A better way to understand a place.</h2><p className="mt-7 max-w-[430px] text-sm leading-7 text-paper/75">We do not ask a listing to speak louder than the place around it. We make the locality, source trail, and meaningful update visible before the next step.</p></div><div><div className="grid border-y border-paper/20 sm:grid-cols-3"><div className="border-b border-paper/20 py-5 sm:border-b-0 sm:border-r sm:pr-5"><p className="font-display text-3xl text-[#efb094]">01</p><p className="mt-2 text-sm text-paper/75">Locality context</p><p className="mt-1 text-xs leading-5 text-paper/55">Street rhythm, access, and everyday cues.</p></div><div className="border-b border-paper/20 py-5 sm:border-b-0 sm:border-r sm:px-5"><p className="font-display text-3xl text-[#efb094]">02</p><p className="mt-2 text-sm text-paper/75">Source review</p><p className="mt-1 text-xs leading-5 text-paper/55">RERA and partner evidence kept in view.</p></div><div className="py-5 sm:pl-5"><p className="font-display text-3xl text-[#efb094]">03</p><p className="mt-2 text-sm text-paper/75">Freshness signal</p><p className="mt-1 text-xs leading-5 text-paper/55">Updates tell you when a fact was checked.</p></div></div><Link href="/guide" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#efb094]">Read our methodology <ArrowUpRight size={16} /></Link></div></div></section>
  </div>;
}
