/* Architech Editorial Terracotta: verified property dossier with trust before spectacle, early facts, gallery depth, and a calm lead action. */
import { ArrowUpRight, BedDouble, Check, Clock3, Heart, MapPin, MessageCircle, Ruler, ShieldCheck } from "lucide-react";
import { Link, useParams } from "wouter";

export default function ListingPage() {
  const { id } = useParams<{ id: string }>();
  const title = id === "garden-courtyard" ? "A garden courtyard in Powai" : id === "light-filled-home" ? "Light across every room" : "A quieter edge of Bandra";
  const locality = id === "garden-courtyard" ? "Powai" : id === "light-filled-home" ? "Khar West" : "Bandra West";
  return <div className="bg-paper pt-[76px] text-ink">
    <section className="container py-8 md:py-12">
      <div className="flex flex-wrap items-center gap-2 text-xs text-ink/55"><Link href="/" className="hover:text-clay">Home</Link><span>/</span><Link href="/buy/mumbai/" className="hover:text-clay">Mumbai</Link><span>/</span><span>{locality}</span><span>/</span><span>{title}</span></div>
      <div className="mt-8 grid gap-4 border-y border-ink/15 bg-limestone p-5 md:grid-cols-[1fr_auto] md:items-center md:p-7">
        <div><p className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[.16em] text-clay"><ShieldCheck size={14} /> RERA verified · source reviewed · updated 2 days ago</p><h1 className="mt-3 max-w-[680px] font-display text-4xl font-medium leading-[.92] tracking-[-.055em] md:text-5xl">{title}</h1><p className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-sm text-ink/60"><span className="flex items-center gap-2"><MapPin size={15} className="text-clay" /> {locality}, Mumbai</span><span className="flex items-center gap-2"><BedDouble size={15} className="text-clay" /> 3 BHK</span><span className="flex items-center gap-2"><Ruler size={15} className="text-clay" /> 1,482 sq ft</span></p></div><div className="border-l border-ink/15 pl-5 md:min-w-[180px]"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-ink/50">Guide price</p><p className="mt-2 font-display text-3xl font-semibold tracking-[-.04em]">₹3.85 Cr</p><p className="mt-1 text-xs text-ink/50">Nivasa Partners</p></div>
      </div>
      <div className="mt-5 grid gap-3 md:grid-cols-[1.4fr_.8fr]"><div className="relative min-h-[320px] overflow-hidden bg-limestone md:min-h-[500px]"><img src="/manus-storage/architech-interior-detail_3d4dda2a.jpg" alt={`${title} interior`} className="h-full w-full object-cover" /><div className="absolute left-5 top-5 bg-paper/90 px-3 py-2 text-[10px] font-semibold uppercase tracking-[.15em] text-ink">Verified interior view</div></div><div className="grid gap-3 md:grid-rows-2"><img src="/manus-storage/architech-material-detail_fc607fb0.jpg" alt="Architectural detail of the property" className="h-full min-h-[180px] w-full object-cover" /><div className="relative overflow-hidden bg-ink"><img src="/manus-storage/architech-locality-editorial_3d96042e.jpg" alt="Neighbourhood around the property" className="h-full w-full object-cover opacity-65" /><div className="absolute inset-0 flex items-end p-5"><span className="text-sm font-semibold text-paper">See the neighbourhood around it <ArrowUpRight size={15} className="ml-1 inline text-[#f0b59b]" /></span></div></div></div></div>
    </section>
    <section className="container pb-16 md:pb-24"><div className="grid gap-12 lg:grid-cols-[1fr_340px]"><div><div className="flex items-start justify-between gap-5"><div><p className="text-sm leading-7 text-ink/60">A light-filled home with a calm material palette and a generous relationship to the neighbourhood outside. The details here are assembled from the partner submission, source review, and the latest meaningful update.</p></div><button className="grid h-11 w-11 shrink-0 place-items-center border border-ink/15 hover:border-clay hover:text-clay" aria-label="Save listing"><Heart size={18} /></button></div><div className="mt-8 grid gap-8 border-t border-ink/15 pt-8 md:grid-cols-2"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-clay">Why it stands out</p><ul className="mt-5 grid gap-3 text-sm text-ink/70"><li className="flex gap-3"><Check size={16} className="shrink-0 text-clay" /> Quiet orientation with natural light</li><li className="flex gap-3"><Check size={16} className="shrink-0 text-clay" /> Walkable everyday conveniences</li><li className="flex gap-3"><Check size={16} className="shrink-0 text-clay" /> Verified partner and source trail</li></ul></div><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-clay">Information trail</p><p className="mt-5 flex items-center gap-2 text-sm text-ink/60"><Clock3 size={15} /> Updated 2 days ago</p><Link href="/guide" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-clay">How we review listings <ArrowUpRight size={15} /></Link></div></div></div><aside className="h-fit border border-ink/15 bg-limestone p-6 md:p-7 lg:sticky lg:top-28"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-clay">Private next step</p><p className="mt-3 font-display text-3xl font-semibold tracking-[-.04em]">Talk to the partner</p><p className="mt-2 text-sm text-ink/55">Your contact details stay private until you choose to share them.</p><div className="mt-7 border-t border-ink/15 pt-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-ink font-display text-lg text-paper">N</div><div><p className="font-semibold">Nivasa Partners</p><p className="text-xs text-ink/55">Verified Mumbai partner</p></div></div></div><button className="mt-7 flex w-full items-center justify-center gap-2 bg-[var(--clay)] px-5 py-4 text-sm font-semibold text-paper transition-transform hover:-translate-y-0.5"><MessageCircle size={17} /> Ask about this home</button></aside></div></section>
  </div>;
}
