"use client";

import Link from "next/link";
import { Handshake, MapPin, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import useTitle from "@/hooks/useTitle";

type InventoryRow = { id: string; title: string; locality: string | null; city: string | null; listerType: string; visibility: string; addressVisibility: string; capabilities: { canRequestExactAddress: boolean; canRelayCall: boolean } };

export default function BrokerInventory() {
  useTitle("Broker inventory");
  const [rows, setRows] = useState<InventoryRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [blocked, setBlocked] = useState<string | null>(null);
  useEffect(() => { fetch("/api/broker/inventory", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) { setBlocked(payload.errors?.join(" ") ?? "A broker plan is required."); return; } setRows(payload.listings ?? []); }).catch(() => setBlocked("Inventory could not be loaded right now.")).finally(() => setLoading(false)); }, []);
  async function collaborate(id: string) { const response = await fetch("/api/broker/collaboration-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ listingId: id, terms: "Please confirm co-broker availability and authorised contact route." }) }); const payload = await response.json(); toast(payload.ok ? "Collaboration request sent." : "Request not sent.", { description: payload.errors?.join(" ") }); }
  async function requestAddress(id: string) { const response = await fetch(`/api/listings/${encodeURIComponent(id)}/address-request`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ purpose: "I need the location to coordinate a legitimate buyer viewing." }) }); const payload = await response.json(); toast(payload.ok ? "Exact-address request sent for approval." : "Address request not sent.", { description: payload.errors?.join(" ") }); }
  async function requestContact(id: string) { const response = await fetch(`/api/listings/${encodeURIComponent(id)}/contact-request`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ purpose: "I have a qualified buyer and want to coordinate a legitimate viewing." }) }); const payload = await response.json(); toast(payload.ok ? "Contact request sent without exposing the advertiser number." : "Contact request not sent.", { description: payload.errors?.join(" ") }); }
  return <div className="bg-paper pb-20 pt-[78px] text-ink"><div className="container py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="kicker text-brick">Broker desk · controlled inventory</p><h1 className="display mt-4 text-[clamp(40px,6vw,72px)]">Verified inventory.</h1><p className="mt-4 max-w-2xl text-base ink-2">Browse listings shared for broker collaboration. Owner numbers remain masked, and exact locations require approval.</p></div><Link href="/broker/plan/" className="touch-44 inline-flex items-center gap-2 border border-brick px-4 py-3 stamp font-semibold text-brick">View plan</Link></div>{loading && <div className="mt-10" role="status">Loading inventory…</div>}{blocked && <div className="mt-10 border border-ember/30 bg-ember/8 p-6"><h2 className="font-display text-2xl">Plan access required</h2><p className="mt-2 max-w-xl text-sm ink-2">{blocked}</p><Link href="/broker/plan/" className="mt-5 inline-flex bg-brick clay-fill px-5 py-3 stamp font-semibold text-cream">Review broker access</Link></div>}{!loading && !blocked && rows.length === 0 && <div className="mt-10 border border-ink/12 bg-card p-6">No broker-shareable inventory is available in your current market.</div>}<div className="mt-10 grid gap-4 lg:grid-cols-2">{rows.map((row) => <article key={row.id} className="border border-ink/12 bg-card p-6"><div className="flex items-start justify-between gap-4"><div><span className="status-badge status-badge-trust stamp font-semibold"><ShieldCheck size={12} className="mr-1 inline" /> {row.visibility === "OWNER_DIRECT" ? "owner direct" : "broker shareable"}</span><h2 className="mt-4 font-display text-2xl">{row.title}</h2><p className="mt-2 flex items-center gap-1.5 text-sm ink-2"><MapPin size={14} /> {row.locality ?? "Locality withheld"}{row.city ? ` · ${row.city}` : ""}</p></div><span className="stamp ink-3">{row.listerType}</span></div><div className="mt-6 flex flex-wrap gap-2 border-t border-ink/10 pt-5"><button type="button" onClick={() => void collaborate(row.id)} className="touch-44 inline-flex items-center gap-2 bg-brick clay-fill px-4 py-2.5 stamp font-semibold text-cream"><Handshake size={14} /> Request collaboration</button><button type="button" onClick={() => void requestContact(row.id)} className="touch-44 border border-ink/20 px-4 py-2.5 stamp font-semibold ink-2">Request contact</button>{row.capabilities.canRequestExactAddress && <button type="button" onClick={() => void requestAddress(row.id)} className="touch-44 border border-ink/20 px-4 py-2.5 stamp font-semibold ink-2">Request location</button>}</div></article>)}</div></div></div>;
}
